imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        #auto_mapping: true
        entity_managers:
            default:
                mappings:
                    FOSUserBundle: ~
                    CountrynsideUserBundle: ~
                    CountrynsideSiteBundle: ~
                    CountrynsidePaymentBundle: ~
                    CountrynsideCalendarBundle: ~
                    payum:
                        is_bundle: false
                        type: xml
                        dir: %kernel.root_dir%/../vendor/payum/core/Payum/Core/Bridge/Doctrine/Resources/mapping

                        # set this dir instead if you use `payum/payum` library
                        #dir: %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Doctrine/Resources/mapping

                        prefix: Payum\Core\Model
                        
                         
# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

#fosuser bundle
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Countrynside\UserBundle\Entity\User
    registration:
        form:
            type: countrynside_user_registration
        confirmation:
            from_email:
                address:        countrynside.adm@gmail.com
                sender_name:    Administrateur
            enabled: true
    service:
            mailer: fos_user.mailer.twig_swift
            
twig:
    paths:
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Resources/views: PayumCore
        %kernel.root_dir%/../vendor/payum/payum/src/Payum/Core/Bridge/Symfony/Resources/views: PayumSymfonyBridge
        
payum:
    security:
        token_storage:
            Countrynside\PaymentBundle\Entity\PaymentToken: { doctrine: orm }

    storages:
        Countrynside\PaymentBundle\Entity\Order: { doctrine: orm }

    contexts:
        myPayment:
            paypal_express_checkout_nvp:
                username:  'philippe.paulos-facilitator_api1.hotmail.fr'
                password:  'V4EKLDFKZFCR8HS7'
                signature: 'AFcWxV21C7fd0v3bYYYRCpSSRl31AFBqutY937koYKVRtgsubJfGNq4m'
                sandbox: true
                
jms_payment_core:
    secret: asecret