fos_user_security:
    resource: "routing/security.xml"

fos_user_register:
    resource: "routing/registration.xml"
    prefix: /inscription

fos_user_profil:
    resource: "routing/profile.xml"
    prefix: /profile