services:
    countrynside_user.registration.form.type:
         class: Countrynside\UserBundle\Form\Type\RegistrationFormType
         tags:
             - { name: form.type, alias: countrynside_user_registration }