<?php

namespace Countrynside\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends EntityRepository {
    
    public function findByMots($mots){
        $queryBuilder = $this->createQueryBuilder('e');
        $i=0;
        foreach($mots as $mot){
            $queryBuilder ->andWhere('e.titre LIKE :titre'.$i.'')
                    ->setParameter('titre'.$i.'', '%'.$mot.'%');
            $i=$i+1;
        }
        return $queryBuilder->getQuery()->getResult();
                
    }
}
